import { Router } from "express";

import { accidentRouter } from "./accident";
import { authRouter } from "./auth";
import { vendorRouter } from "./vendor";
import { checkRole, isAuth } from "../middlewares";
import { userRouter } from "./user";
import { inspectionRouter } from "./inspection";
import { brokerRouter } from "./broker";
import { clientRouter } from "./client";
import { alertRouter } from "./alert";
import { drugTestRouter } from "./drug_test";
import { applicantRouter } from "./applicant";
import { deviceRouter } from "./device";
import { driversRouter } from "./driver";
import { driverBoardsRouter } from "./driver_board";
import { trainingRouter } from "./training";
import { companyRouter } from "./company";
import { payrollRouter } from "./payroll";
import { loadRouter } from "./load";
import { permitRouter } from "./permit";
import { sambaCredentialRouter } from "./samba_credential";
import { incidentRouter } from "./incident";
import { truckRouter } from "./truck";
import payablesRouter from "./payables";
import { serviceRouter } from "./service";
import { trailerRouter } from "./trailer";
import { permissionRouter } from "./permission";
import { roleRouter } from "./role";
import { userRoleRouter } from "./user_role";
import { eldRouter } from "./eld";
import { factoringRouter } from "./factoring";
import { bcarrierRouter } from "./bcarrier";
import { bcontactRouter } from "./bcontact";
import { bcustomerRouter } from "./bcustomer";
import { bquoteRouter } from "./bquote";
import { binvoiceRouter } from "./binvoice";
import { checkinCheckoutRouter } from "./checkin_checkout";
import { locationRouter } from "./location";

export const root = Router();
const bRouter = Router();
const cRouter = Router();
const aRouter = Router();

root.use("/broker", isAuth, checkRole, bRouter);
root.use("/carrier", isAuth, checkRole, cRouter);
root.use("/admin", isAuth, checkRole, aRouter);

root.use("/auth", authRouter);
root.use("/client", clientRouter);
root.use("/companies", companyRouter);

aRouter.use("/users", userRouter);

cRouter.use("/users", userRouter);
cRouter.use("/accidents", accidentRouter);
cRouter.use("/vendors", vendorRouter); 
cRouter.use("/brokers", brokerRouter); 
cRouter.use("/inspections", inspectionRouter); 
cRouter.use("/alerts", alertRouter); 
cRouter.use("/drug-tests", drugTestRouter); 
cRouter.use("/applicants", applicantRouter); 
cRouter.use("/devices", deviceRouter); 
cRouter.use("/drivers", driversRouter); 
cRouter.use("/driver-boards", driverBoardsRouter); 
cRouter.use("/trainings", trainingRouter);
cRouter.use("/loads", loadRouter);
cRouter.use("/payroll", payrollRouter);
cRouter.use("/permits", permitRouter);
cRouter.use("/samba/csa/credentials", sambaCredentialRouter);
cRouter.use("/incidents", incidentRouter);
cRouter.use("/trucks", truckRouter);
cRouter.use("/payables", payablesRouter);
cRouter.use("/services", serviceRouter);
cRouter.use("/trailers", trailerRouter);
cRouter.use("/eld", eldRouter);
cRouter.use("/factorings", factoringRouter);
cRouter.use("/permissions", permissionRouter);
cRouter.use("/roles", roleRouter);
cRouter.use("/user-roles", userRoleRouter);
cRouter.use("/checkin-checkouts", checkinCheckoutRouter);
cRouter.use("/locations", locationRouter);

bRouter.use("/loads", loadRouter);
bRouter.use("/users", userRouter);
bRouter.use("/carriers", bcarrierRouter);
bRouter.use("/contacts", bcontactRouter);
bRouter.use("/customers", bcustomerRouter);
bRouter.use("/quotes", bquoteRouter);
bRouter.use("/invoices", binvoiceRouter);