paths:
 /carrier/trainings:
    get:  
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Retrieve multiple trainings
      description: Fetches a paginated list of trainings based on query parameters.
      parameters:
        - name: page_number
          in: query
          description: Page number for pagination.
          required: false
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          description: Number of trainings per page.
          required: false
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  page_size:
                    type: integer
                    example: 10
                  page_number:
                    type: integer
                    example: 1
                  total_pages:
                    type: integer
                    example: 1
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ITraining'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    post:
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Schedule a new training
      description: Validates the new training's data, then schedules it in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ITrainingCreate'
      responses:
        201:
          description: Training is scheduled.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: The id of the new training.
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
 /carrier/trainings/search/{driver_id}:
    get:
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Retrieve multiple trainings
      description: Fetches a paginated list of trainings based on query parameters.
      parameters:
        - name: driver_id
          in: path
          description: ID of the driver to retrieve trainings for.
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  page_size:
                    type: integer
                    example: 10
                  page_number:
                    type: integer
                    example: 1
                  total_pages:
                    type: integer
                    example: 1
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ITraining'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
 /carrier/trainings/{training_id}:
    get:
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Retrieve a single training
      description: Fetches a single training by ID.
      parameters:
        - name: training_id
          in: path
          description: ID of the training to retrieve.
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Successfully retrieved the training.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ITraining'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    put:
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Update a training record
      description: Updates details of a single training by ID.
      parameters:
        - name: training_id
          in: path
          description: ID of the training to update.
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ITrainingUpdate'
      responses:
        200:
          description: Successfully updated the training.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Training with ID successfully updated
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags: [Trainings]
      security:
        - bearerAuth: []
      summary: Cancel a training session
      description: Deletes a single training session by ID.
      parameters:
        - name: training_id
          in: path
          description: ID of the training to cancel.
          required: true
          schema:
            type: integer
            example: 1
      responses:
        204:
          description: Successfully canceled the training.
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
